# -*- coding: utf-8 -*-
# Auto-generated by utils/mitmproxy_mock.py
#
# 使用方式（示例）：
#   mitmproxy --mode regular --listen-host 127.0.0.1 --listen-port 8080 -s <this_file.py>
#
# 规则说明：
# - 按 method + path 精确匹配
# - 可选 query 匹配（只要求包含指定key且值命中列表/单值）
#

import json
from datetime import datetime
from mitmproxy import http


RULES = {
  "responses": [
    {
      "method": "GET",
      "path": "/api/data",
      "response": {
        "status": 200,
        "body": {
          "status": "success",
          "data": []
        }
      }
    }
  ]
}


def _match_query(actual_query: dict, expected_query: dict) -> bool:
    for k, expected_values in (expected_query or {}).items():
        if k not in actual_query:
            return False
        if not isinstance(expected_values, list):
            expected_values = [expected_values]
        # mitmproxy query 形如 MultiDictView，可用 get_all
        try:
            actual_values = actual_query.get_all(k)
        except Exception:
            actual_values = [actual_query.get(k)]
        if not actual_values:
            return False
        if str(actual_values[0]) not in [str(x) for x in expected_values]:
            return False
    return True


class JsonRuleMock:
    def request(self, flow: http.HTTPFlow) -> None:
        try:
            method = flow.request.method.upper()
            path = flow.request.path.split("?", 1)[0]
            query = flow.request.query

            for item in RULES.get("responses", []):
                if str(item.get("method", "GET")).upper() != method:
                    continue
                if str(item.get("path", "")) != path:
                    continue

                expected_query = item.get("query")
                if expected_query and not _match_query(query, expected_query):
                    continue

                resp = item.get("response", {}) or {}
                status = int(resp.get("status", 200))
                body = resp.get("body", {})
                if body is None:
                    body = {}

                payload = json.dumps(body, ensure_ascii=False).encode("utf-8")
                flow.response = http.Response.make(
                    status,
                    payload,
                    {"Content-Type": "application/json; charset=utf-8"}
                )

                # 记录到 mitmproxy event log
                flow.comment = f"[MOCK] {method} {path} -> {status} @ {datetime.now().isoformat(timespec='seconds')}"
                return
        except Exception:
            # 出错时不拦截，交给真实服务
            return


addons = [JsonRuleMock()]
