#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""
mitmproxy Mock 脚本生成器

用途：
- 将项目现有的 mock 规则(JSON)转换为 mitmproxy addon 脚本
- 在 HTTPS 场景下，配合 mitmproxy 证书安装，可对 HTTPS 流量解密并按规则返回响应

规则格式（与GUI规则编辑器一致）：
{
  "responses": [
    {
      "method": "GET",
      "path": "/api/data",
      "query": {"k": ["v1", "v2"]},   # 可选
      "response": {"status": 200, "body": {"a": 1}}
    }
  ]
}
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any, Dict


def normalize_rules(rules: Any) -> Dict[str, Any]:
    if not isinstance(rules, dict):
        return {"responses": []}
    if "responses" not in rules or not isinstance(rules.get("responses"), list):
        return {"responses": []}
    return rules


def generate_mitmproxy_script(rules: Dict[str, Any]) -> str:
    """
    生成可编辑的 mitmproxy addon 脚本。
    说明：脚本会把 rules 内联进脚本，便于单文件分发；你也可以改成读取外部文件。
    """
    rules = normalize_rules(rules)
    rules_json = json.dumps(rules, ensure_ascii=False, indent=2)

    return f"""# -*- coding: utf-8 -*-
# Auto-generated by utils/mitmproxy_mock.py
#
# 使用方式（示例）：
#   mitmproxy --mode regular --listen-host 127.0.0.1 --listen-port 8080 -s <this_file.py>
#
# 规则说明：
# - 按 method + path 精确匹配
# - 可选 query 匹配（只要求包含指定key且值命中列表/单值）
#

import json
from datetime import datetime
from mitmproxy import http


RULES = {rules_json}


def _match_query(actual_query: dict, expected_query: dict) -> bool:
    for k, expected_values in (expected_query or {{}}).items():
        if k not in actual_query:
            return False
        if not isinstance(expected_values, list):
            expected_values = [expected_values]
        # mitmproxy query 形如 MultiDictView，可用 get_all
        try:
            actual_values = actual_query.get_all(k)
        except Exception:
            actual_values = [actual_query.get(k)]
        if not actual_values:
            return False
        if str(actual_values[0]) not in [str(x) for x in expected_values]:
            return False
    return True


class JsonRuleMock:
    def request(self, flow: http.HTTPFlow) -> None:
        try:
            method = flow.request.method.upper()
            path = flow.request.path.split("?", 1)[0]
            query = flow.request.query

            for item in RULES.get("responses", []):
                if str(item.get("method", "GET")).upper() != method:
                    continue
                if str(item.get("path", "")) != path:
                    continue

                expected_query = item.get("query")
                if expected_query and not _match_query(query, expected_query):
                    continue

                resp = item.get("response", {{}}) or {{}}
                status = int(resp.get("status", 200))
                body = resp.get("body", {{}})
                if body is None:
                    body = {{}}

                payload = json.dumps(body, ensure_ascii=False).encode("utf-8")
                flow.response = http.Response.make(
                    status,
                    payload,
                    {{"Content-Type": "application/json; charset=utf-8"}}
                )

                # 记录到 mitmproxy event log
                flow.comment = f"[MOCK] {method} {path} -> {status} @ {{datetime.now().isoformat(timespec='seconds')}}"
                return
        except Exception:
            # 出错时不拦截，交给真实服务
            return


addons = [JsonRuleMock()]
"""


def write_mitmproxy_script(script_path: str | Path, rules: Dict[str, Any]) -> str:
    p = Path(script_path)
    p.parent.mkdir(parents=True, exist_ok=True)
    script = generate_mitmproxy_script(rules)
    p.write_text(script, encoding="utf-8")
    return str(p)

